# Generated by Django 4.0.5 on 2022-06-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarsStoreApp', '0001_initial'),
    ]

    operations = [

    ]
