# Generated by Django 4.0.5 on 2022-06-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsStoreApp', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=100)),
            ],
        ),
    ]
